---
# Our pre-commit hook definition.
# Required for repositories that provide pre-commit hook implementations.
- id: im-oval
  name: OpenAPI Validator
  description: This hook validates OpenAPI files
  entry: oval
  language: python
